### ISSUE TITLE
release.1.0.2 fails to build on 4.00.1

### ISSUE THREAD

**Issue by avsm** [andrenth/release#2]
In automated tests, and this also causes `spf` to fail. Looks like its fixed in trunk; any chance of a new release, and should we mark 1.0.2 as broken (or should it work with some other compiler variant or something?).

```
ocamlfind ocamlc -c -g -annot -warn-error A -I lib/buffer -I lib/util -package lwt.unix -package lwt.syntax -package lwt -syntax camlp4o -I lib/core -I lib/buffer -I lib/util -o lib/core/release_ipc.cmo lib/core/release_ipc.ml
+ ocamlfind ocamlc -c -g -annot -warn-error A -I lib/buffer -I lib/util -package lwt.unix -package lwt.syntax -package lwt -syntax camlp4o -I lib/core -I lib/buffer -I lib/util -o lib/core/release_ipc.cmo lib/core/release_ipc.ml
File "lib/core/release_ipc.ml", line 149, characters 25-38:
Error: Unbound value read_request'
Command exited with code 2.
```
